name: 'add-issue-to-project'
on: 
  issues:
    types: [opened, reopened]
jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          milestone: "1.0"
          project_column: "To do"
          project: "Test"